// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.TicTacToe.Database;

#nullable disable

namespace WebApi.TicTacToe.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230321112702_add new models")]
    partial class addnewmodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApi.TicTacToe.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.PlayersMakeMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayersMakeMoves");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.ResultGamePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ResultGame")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ResultGamePlayers");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("HostId")
                        .HasColumnType("int");

                    b.Property<string>("NameRoom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusRoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HostId")
                        .IsUnique()
                        .HasFilter("[HostId] IS NOT NULL");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.RoomPlayers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomPlayers");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.PlayersMakeMove", b =>
                {
                    b.HasOne("WebApi.TicTacToe.Models.Game", "Game")
                        .WithMany("PlayersMakeMoves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.TicTacToe.Models.User", "Player")
                        .WithMany("PlayerMakeMoves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.ResultGamePlayer", b =>
                {
                    b.HasOne("WebApi.TicTacToe.Models.Game", "Game")
                        .WithMany("ResultGamePlayers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.TicTacToe.Models.User", "Player")
                        .WithMany("ResultGamePlayer")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.Room", b =>
                {
                    b.HasOne("WebApi.TicTacToe.Models.User", "Host")
                        .WithOne("Room")
                        .HasForeignKey("WebApi.TicTacToe.Models.Room", "HostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Host");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.RoomPlayers", b =>
                {
                    b.HasOne("WebApi.TicTacToe.Models.User", "Player")
                        .WithOne("RoomPlayer")
                        .HasForeignKey("WebApi.TicTacToe.Models.RoomPlayers", "PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.TicTacToe.Models.Room", "Room")
                        .WithMany("RoomPlayers")
                        .HasForeignKey("RoomId");

                    b.Navigation("Player");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.Game", b =>
                {
                    b.Navigation("PlayersMakeMoves");

                    b.Navigation("ResultGamePlayers");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.Room", b =>
                {
                    b.Navigation("RoomPlayers");
                });

            modelBuilder.Entity("WebApi.TicTacToe.Models.User", b =>
                {
                    b.Navigation("PlayerMakeMoves");

                    b.Navigation("ResultGamePlayer");

                    b.Navigation("Room");

                    b.Navigation("RoomPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
